#!/usr/bin/env python
import PyPDF2 
import sys 

position = 1
arguments = len(sys.argv) - 1
pdfWriter = PyPDF2.PdfFileWriter()
while (arguments >= position):
  print sys.argv[position]
  pdfFile = open(sys.argv[position], 'rb')
  pdfReader = PyPDF2.PdfFileReader(pdfFile)
  for pageNum in range(pdfReader.numPages):
     pageObj = pdfReader.getPage(pageNum)
     pdfWriter.addPage(pageObj)
  position = position + 1  
pdfOutputFile = open('MergedFiles.pdf', 'wb')
pdfWriter.write(pdfOutputFile)
pdfOutputFile.close()
